// <auto-generated />
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(DBCont))]
    [Migration("20201030204709_nueva database")]
    partial class nuevadatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("BlazorApp1.Data.Detalles", b =>
                {
                    b.Property<int>("IDDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recurso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("IDDetalle");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("BlazorApp1.Data.Recursos", b =>
                {
                    b.Property<int>("IDRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("IDRecurso");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("BlazorApp1.Data.Tareas", b =>
                {
                    b.Property<int>("IDTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsable")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vencimiento")
                        .HasColumnType("TEXT");

                    b.Property<bool>("bo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IDTarea");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("BlazorApp1.Data.Usuarios", b =>
                {
                    b.Property<int>("IDUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.HasKey("IDUser");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
